// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/recura-hero.scene.json";
import recipe1 from "./scenes/recura-sidebar.scene.json";
import recipe2 from "./scenes/recura-signin.scene.json";
export const sceneModules = {
  "src/flute/scenes/recura-hero.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/recura-hero.tsx": () => import("./scenes/recura-hero"),
  "src/flute/scenes/recura-sidebar.scene.json": async () => ({default:recipe1}),
  "src/flute/scenes/recura-sidebar.tsx": () => import("./scenes/recura-sidebar"),
  "src/flute/scenes/recura-signin.scene.json": async () => ({default:recipe2}),
  "src/flute/scenes/recura-signin.tsx": () => import("./scenes/recura-signin"),
};
